# coreutils (for me)
brew "fzf"
brew "ripgrep"
brew "git"
brew "tmux"
brew "tree"
brew "watch"
brew "jq"
brew "yq"
brew "just"
brew "sops"
brew "sqlite"
brew "tig"
brew "stow"
brew "starship"
brew "btop"

# terminal

# editor
# -------- (vim) --------
brew "neovim"
brew "vim"
brew "fontconfig"
brew "tree-sitter-cli"
# -------- (emacs) --------
brew "emacs"

# kubernetes
brew "helm"
brew "kubernetes-cli"
brew "kind"
brew "k9s"
brew "kustomize"

# cloud
brew "awscli"

# github
brew "gh"

# coreutils
brew "bash"
brew "coreutils"
brew "curl"
brew "pkgconf"
brew "gnupg"

# dev-general
brew "bazel"
brew "mise"
brew "vale"
brew "wrk"

# dev-go
brew "go"
brew "goreleaser"
brew "golangci-lint"
brew "nfpm"

# dev-protobuf
brew "buf"
brew "protobuf"
#brew "grpcui"
#brew "grpcurl"
#brew "jsonnet"

# dev-docker
brew "crane"
brew "dive"
brew "hadolint"
brew "container-structure-test"

# dev-cxx
brew "clang-format"
brew "llvm"
brew "bear"
brew "cmake"
brew "lcov"

# dev-lua
brew "lua"
brew "luajit"

# dev-rust
brew "rustup"

# dev-shell
brew "shellcheck"

# dev-python
brew "uv"

# software
brew "varnish"

# cask
cask "google-chrome"
cask "obsidian"
cask "spotify"
#cask "docker-desktop"
cask "dropbox"
cask "macpass"
cask "alacritty"